### ISSUE TITLE
Broken with certain Emacs versions

### ISSUE THREAD

**Issue by purcell** [dgutov/highlight-escape-sequences#2]
In Emacs 23.3, at least, the latest code is incompatible with rx:

```
In toplevel form:

highlight-escape-sequences.el:100:1:Error: rx `any' needs argument(s)
```

Perhaps there's a workaround, otherwise a `Package-Requires:` dependency on the appropriate Emacs version would be advisable. (I found this via the [smoke test build](https://travis-ci.org/purcell/emacs.d/jobs/73296511) I run for my emacs config on various emacsen.)

**Comment by dgutov** [comment]
Thanks for letting me know. Hopefully, this does it, please check.

**Comment by purcell** [comment]
Yes, great - thanks!
