### ISSUE TITLE
font-lock-add-keywords make this package not work.

### ISSUE THREAD

**Issue by zw963** [dgutov/highlight-escape-sequences#4]
Following will result in highlight not make effect.

``` cl
 (font-lock-add-keywords
              nil '(("\\<\\(FIX\\|TODO\\|FIXME\\|HACK\\|REFACTOR\\):"
                     1 font-lock-warning-face t)))
```

What is the correct usage to add a new keyboards face?

Thanks.

**Comment by dgutov** [comment]
Works for me.

How do you reproduce this?

**Comment by zw963** [comment]
It at least not worked in ruby-mode. emacs 24.5.

``` cl
(add-hook 'prog-mode-hook
          '(lambda ()
             (font-lock-add-keywords
              nil '(("\\<\\(FIX\\|TODO\\|FIXME\\|HACK\\|REFACTOR\\):"
                     1 font-lock-warning-face t)))
             ))

(require 'highlight-escape-sequences)
(add-hook 'ruby-mode-hook 'turn-on-hes-mode)
```

And, then open one rbfile.

**Comment by dgutov** [comment]
What's the next step?

Looks fine here so far.

**Comment by zw963** [comment]
No next step, I test with `emacs -Q`, if no fon-lock definition, work correct.

i found a strange things, with this code, when I start emacs open a rb file,
hes-mode is not enable. even i enable it maually not make effect.
only not this font-lock definition, all work well.

**Comment by zw963** [comment]
so i think:

``` cl
(font-lock-add-keywords
              nil '(("\\<\\(FIX\\|TODO\\|FIXME\\|HACK\\|REFACTOR\\):"
                     1 font-lock-warning-face t)))
```

is not a considerable method to add highlight to keyword?

**Comment by dgutov** [comment]
Have you seen the usage instruction? It's very short.

**Comment by dgutov** [comment]
For `hes-mode`, I mean. Your `font-lock-add-keywords` setup works fine.

**Comment by zw963** [comment]
It very eash to produce.

## 1. Emacs -Q

## 2. Copy following code to scratch buffer, and eval

``` cl
(add-to-list 'load-path "your load path")

(add-hook 'prog-mode-hook
          '(lambda ()
             (font-lock-add-keywords
              nil '(("\\<\\(FIX\\|TODO\\|FIXME\\|HACK\\|REFACTOR\\):"
                     1 font-lock-warning-face t)))
             ))

(require 'highlight-escape-sequences)
(add-hook 'ruby-mode-hook 'turn-on-hes-mode)
```

## 3. open a exist rb file, only a string:

``` ruby
puts "i has a\n new line\n"
```

## 4. \n is not different.

**Comment by zw963** [comment]
## 1. Emacs -Q

## 2. Copy following code to scratch buffer, and eval-buffer

(add-to-list 'load-path "your load path")
(require 'highlight-escape-sequences)
(add-hook 'ruby-mode-hook 'turn-on-hes-mode)

## 3. open a exist rb file, only a string:

puts "i has a\n new line\n"

## 4. we could see \n is weighted.

**Comment by zw963** [comment]
GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, X toolkit, Xaw scroll bars) of 2016-04-25

**Comment by dgutov** [comment]
> (add-hook 'ruby-mode-hook 'turn-on-hes-mode)

That's not the way to use this mode.

**Comment by zw963** [comment]
OK, it worked like this:

``` cl
(require 'highlight-escape-sequences)
(add-hook 'prog-mode-hook 'turn-on-hes-mode)
(add-hook 'emacs-lisp-mode '(turn-off-hes-mode))
```

In fact, i just want to enable this mode for ruby-mode.
i dont know how to achieve this.

thanks.

**Comment by dgutov** [comment]
> In fact, i just want to enable this mode for ruby-mode

To do that, you can change `hes-mode-alist` before enabling `hes-mode`.
