### ISSUE TITLE
go-mode support

### ISSUE THREAD

**Issue by vbauerster** [dgutov/highlight-escape-sequences#5]
Nothing is highlighted in `*.go` files.
Could you please add support for go mode?

**Comment by dgutov** [comment]
Sure. Does it have the same escapes as C?

**Comment by vbauerster** [comment]
Yes. A good option will be to highlight special printf symbols as well. For example `printf("num: %d\n", 0)`. Highlighting `%d` seems to be very consistent.

**Comment by dgutov** [comment]
> Yes

Added, thanks.

> For example printf("num: %d\n", 0). Highlighting %d seems to be very consistent

Out of scope for this package, sorry. I'd consider a PR adding this for all supported languages, but we'd probably have to change the name as well.
