### ISSUE TITLE
Add version tag for MELPA stable

### ISSUE THREAD

**Issue by edwintorok** [dgutov/highlight-escape-sequences#8]
Hi!

[MELPA Stable](http://stable.melpa.org/) is the new younger sibling of MELPA for users who'd rather run only stable versions of packages (MELPA can be a bit rocky since every commit comprises a new release), and it would be useful if highlight-escape-sequences could be installed via Stable.

Fortunately it's also really easy to support—all you have to do is define a tag in the `v...` format and you're done. I'd submit a PR if I could, but since tags are global to a project, that's not something possible via PR.

If you're cool with this idea, this should be all you have to do to make it happen:

```sh
$ git tag v0.4.0 08d846a7aa748209d65fecead2b6a766c3e5cb41
$ git push origin v0.4.0
```

(Of course, confirm that 08d846a7aa748209d65fecead2b6a766c3e5cb41 is the appropriate commit for the release, but it's the one where the version number was bumped to 0.4.0 so I suspect it is.)

Thanks for your time and consideration!

**Comment by dgutov** [comment]
So, about MELPA Stable... this package is already distributed via [GNU ELPA](http://elpa.gnu.org/packages/), so I'd rather avoid the duplication (as well as creating extra work for the other repository). Is there a problem for you to use it?

But thank you for the reminder: I've pushed the version 0.4 just now. It was stuck on 0.3 before.

**Comment by edwintorok** [comment]
Ah hadn't realised it is on ELPA too (it shows up on MELPA as well here: https://melpa.org/#/?q=highlight-escape).

**Comment by dgutov** [comment]
It's fine for it to be on MELPA (because it's for snapshots). MELPA Stable, less useful here.
